=== camenduru/advanced-live-portrait-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "LivePortrait: Efficient Portrait Animation with Stitching and Retargeting Control",
      "author": "Jianzhu Guo, Dingyun Zhang, Xiaoqiang Liu, Zhizhou Zhong, Yuan Zhang, Pengfei Wan, Di Zhang",
      "page": "https://liveportrait.github.io/",
      "paper": "https://arxiv.org/abs/2407.03168",
      "code": "https://github.com/KwaiVGI/LivePortrait",
      "jupyter": "https://github.com/camenduru/AdvancedLivePortrait-jupyter",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/advanced-live-portrait.ipynb",
      "tags": [
        "Image to Image"
      ],
      "widget": "readme"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "input_image_check"
    },
    "input_image_check": {
      "type": "string",
      "description": "Input Image URL",
      "widget": "textarea"
    },
    "rotate_pitch": {
      "type": "number",
      "description": "rotate_pitch",
      "minimum": -20,
      "maximum": 20,
      "widget": "range"
    },
    "rotate_yaw": {
      "type": "number",
      "description": "rotate_yaw",
      "minimum": -20,
      "maximum": 20,
      "widget": "range"
    },
    "rotate_roll": {
      "type": "number",
      "description": "rotate_roll",
      "minimum": -20,
      "maximum": 20,
      "widget": "range"
    },
    "blink": {
      "type": "number",
      "description": "blink",
      "minimum": -20,
      "maximum": 5,
      "widget": "range"
    },
    "eyebrow": {
      "type": "number",
      "description": "eyebrow",
      "minimum": -10,
      "maximum": 15,
      "widget": "range"
    },
    "wink": {
      "type": "number",
      "description": "wink",
      "minimum": 0,
      "maximum": 25,
      "widget": "range"
    },
    "pupil_x": {
      "type": "number",
      "description": "pupil_x",
      "minimum": -15,
      "maximum": 15,
      "widget": "range"
    },
    "pupil_y": {
      "type": "number",
      "description": "pupil_y",
      "minimum": -15,
      "maximum": 15,
      "widget": "range"
    },
    "aaa": {
      "type": "number",
      "description": "aaa",
      "minimum": -30,
      "maximum": 120,
      "widget": "range"
    },
    "eee": {
      "type": "number",
      "description": "eee",
      "minimum": -20,
      "maximum": 15,
      "widget": "range"
    },
    "woo": {
      "type": "number",
      "description": "woo",
      "minimum": -20,
      "maximum": 15,
      "widget": "range"
    },
    "smile": {
      "type": "number",
      "description": "smile",
      "minimum": -0.3,
      "maximum": 1.3,
      "widget": "range"
    },
    "src_ratio": {
      "type": "number",
      "description": "src_ratio",
      "minimum": 0,
      "maximum": 1,
      "widget": "hidden"
    },
    "sample_ratio": {
      "type": "number",
      "description": "sample_ratio",
      "minimum": -0.2,
      "maximum": 1.2,
      "widget": "hidden"
    },
    "crop_factor": {
      "type": "number",
      "description": "crop_factor",
      "widget": "hidden"
    },
    "sample_parts": {
      "type": "string",
      "description": "sample_parts",
      "widget": "hidden"
    },
    "example": {
      "type": "string",
      "image1": "https://fakeimg.pl/640x960/282828/eae0d0/?text=input#.png",
      "image2": "https://files.catbox.moe/f1cpjc.png",
      "image3": "https://fakeimg.pl/640x960/282828/eae0d0/?text=output#.png",
      "image4": "https://files.catbox.moe/jglhsp.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/advanced-live-portrait-tost/model.json
{
  "input_image_check": "https://files.catbox.moe/f1cpjc.png",
  "rotate_pitch": 0.0,
  "rotate_yaw": 0.0,
  "rotate_roll": 0.0,
  "blink": 0.0,
  "eyebrow": 0.0,
  "wink": 0.0,
  "pupil_x": 0.0,
  "pupil_y": 0.0,
  "aaa": 0.0,
  "eee": 0.0,
  "woo": 0.0,
  "smile": 1.3,
  "src_ratio": 0.0,
  "sample_ratio": 0.0,
  "sample_parts": "OnlyExpression",
  "crop_factor": 1.7
}
